#!/usr/bin/env python3
"""
GREEN-036: build report.pdf from the verified run artifacts using reportlab.

Reads:
    data/census_summary.json   (produced by verify_solution.py)
    data/run_output.txt        (captured verbatim console output)

Writes:
    report.pdf

report.tex keeps its own inline verbatim copy of data/run_output.txt
(no external \input), so it compiles standalone under any TeX install.
"""

import json
import textwrap
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (KeepTogether, PageBreak, Paragraph,
                                Preformatted, SimpleDocTemplate, Spacer,
                                Table, TableStyle)

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
SUMMARY = json.loads((DATA / "census_summary.json").read_text())
RUNLOG = (DATA / "run_output.txt").read_text()

# guard against building a PDF around stale/different run data
assert SUMMARY["X"] == 10 ** 8 and SUMMARY["F_X"] == 55939931, "stale summary"
assert len(SUMMARY["decade_cumulative"]) == 8

# ----------------------------------------------------------------------
# styles
# ----------------------------------------------------------------------
ss = getSampleStyleSheet()
BASE = "Helvetica"
MONO = "Courier"

def st(name, **kw):
    d = dict(fontName=BASE, fontSize=9.5, leading=13, alignment=TA_JUSTIFY,
             spaceAfter=5)
    d.update(kw)
    return ParagraphStyle(name, **d)

S_TITLE = st("t", fontName="Helvetica-Bold", fontSize=16, leading=20,
             alignment=TA_CENTER, spaceAfter=10)
S_SUB = st("s", fontSize=10.5, leading=14, alignment=TA_CENTER,
           textColor=colors.HexColor("#333333"), spaceAfter=14)
S_H1 = st("h1", fontName="Helvetica-Bold", fontSize=12.5, leading=15,
          spaceBefore=12, spaceAfter=6, alignment=0)
S_BODY = st("b")
S_NOTE = st("n", fontSize=8.7, leading=11.5,
            textColor=colors.HexColor("#444444"))
S_CAP = st("cap", fontSize=8.2, leading=10.5, alignment=TA_CENTER,
           textColor=colors.HexColor("#555555"), spaceBefore=2)
S_MONO = ParagraphStyle("m", fontName=MONO, fontSize=6.4, leading=7.6)
S_ABS = st("abs", fontSize=9.5, leftIndent=18, rightIndent=18)

# ----------------------------------------------------------------------
# content helpers
# ----------------------------------------------------------------------

def P(text, style=S_BODY):
    return Paragraph(text, style)


def table(rows, widths, header=True, fontsize=8.2):
    t = Table(rows, colWidths=widths, hAlign="CENTER")
    cmds = [
        ("FONTNAME", (0, 0), (-1, -1), BASE),
        ("FONTSIZE", (0, 0), (-1, -1), fontsize),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#999999")),
        ("TOPPADDING", (0, 0), (-1, -1), 2.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ]
    if header:
        cmds += [("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                 ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EDEDED"))]
    t.setStyle(TableStyle(cmds))
    return t


story = []

# ----------------------------------------------------------------------
# title & abstract
# ----------------------------------------------------------------------
story.append(P("On the Multiplicatively Closed Set Generated by 2 and 3", S_TITLE))
story.append(P("Partial results, an exact census up to 10^8, and a rejected "
               "mean-field heuristic", S_SUB))
story.append(P("Research dossier for Ben Green's open problem GREEN-036 "
               "(100 Open Problems, Number Theory) - August 25, 2026.<br/>"
               "Source: https://www.unsolvedmath.com/problems/GREEN-036 - "
               "status: <b>OPEN</b>", S_SUB))

story.append(P("<b>Abstract.</b> Let A be the smallest set of positive integers "
               "containing 2 and 3 and closed under the operation "
               "(a1,a2) |-> a1*a2 - 1. Green's problem GREEN-036 asks whether A "
               "has positive asymptotic density. <b>The problem remains open.</b> "
               "This dossier contributes: (i) complete proofs of a "
               "well-foundedness structure theorem, of the modular obstruction "
               "(Lemma A: A avoids 1 mod 3, whence upper density d*(A) &lt;= 2/3), "
               "and of an explicit floor((floor(log2 N)-1)^2/4) ~ 0.5203 (ln N)^2 "
               "lower bound (Lemma B); (ii) an exact, independently cross-checked "
               "census F(10^8) = |A ^ [1,10^8]| = 55,939,931 with per-decade "
               "statistics showing monotonically rising density 0.500 -> 0.559 "
               "and local power-law exponents descending to 1.0079; (iii) a "
               "mean-field self-consistency heuristic sum_{b in A} b^-(1+alpha) "
               "= 1 predicting alpha* = 0.4734, which is quantitatively rejected "
               "by the census (factor 9124), indicating that membership "
               "correlations, not pseudorandomness, govern A; and (iv) a residue "
               "census showing that among all moduli m &lt;= 500 only m = 3 "
               "yields a proper closed residue set, so no improvement on 2/3 is "
               "known. Statements are labeled [PROVEN], [COMPUTED], or "
               "[HEURISTIC] throughout.", S_ABS))
story.append(Spacer(1, 4 * mm))

# ----------------------------------------------------------------------
# 1 problem
# ----------------------------------------------------------------------
story.append(P("1. Problem statement and status", S_H1))
story.append(P("Let A be minimal with 2, 3 in A and a1, a2 in A implying "
               "a1*a2 - 1 in A. Question: does the asymptotic density "
               "d(A) = lim F(N)/N exist and satisfy d(A) &gt; 0, where "
               "F(N) = |A ^ [1,N]|? The question is <b>open</b>; nothing here "
               "settles it. Sections 2-5 establish partial results with proofs, "
               "Section 6 reports an exact computational census, and Section 7 "
               "derives a heuristic together with its own empirical rejection."))

# ----------------------------------------------------------------------
# 2 structure + algorithm
# ----------------------------------------------------------------------
story.append(P("2. Well-foundedness, exact characterization, and generation "
               "algorithm", S_H1))
story.append(P("<b>Structural fact [PROVEN].</b> 1 is not in A (seeds are 2, 3; "
               "ab - 1 &gt;= 2*2 - 1 = 3 for a,b &gt;= 2), and whenever "
               "n = a1*a2 - 1 with a1,a2 in A one has a1,a2 &gt;= 2 and hence "
               "a1, a2 &lt;= (n+1)/2 &lt; n. Values strictly decrease along any "
               "generation tree toward its leaves."))
story.append(P("<b>Theorem 1 (exact characterization) [PROVEN].</b> n is in A "
               "if and only if n is 2 or 3, or n = ab - 1 for some a,b in A. "
               "<i>Proof.</i> Minimality gives one direction directly: if "
               "n &gt; max(a,b) equals ab - 1 with a,b in A then n cannot be "
               "excluded by any closed set containing the seeds, induction on "
               "max(a,b) being well-founded by the structural fact. Conversely "
               "the set {2,3} u {ab-1 : a,b in A} is contained in A by closure. "
               "&#9633;"))
story.append(P("This makes A the least fixed point of S |-> S u {ab-1} and "
               "justifies the increasing-order dynamic program used by the "
               "verifier: membership bits in a bytearray; a min-heap of "
               "discovered-but-unexpanded values; a sorted partner list holding "
               "A ^ [1, sqrt(X)]. Each popped minimum m is expanded against "
               "partners a &lt;= min(m, X//m) &lt;= sqrt(X)."))
story.append(P("<b>Theorem 2 (exactness) [PROVEN].</b> At termination the marked "
               "bytes are exactly A ^ [1,X]. <i>Proof.</i> Soundness is clear: "
               "inserted values ma - 1 use factors already certified to be in A. "
               "For completeness note pushes always exceed the popped value "
               "(ma - 1 &gt;= 2m - 1 &gt; m), so pops occur in increasing order; "
               "by strong induction on n, before any pop of value &gt; n all "
               "elements of A ^ [1,n] are discovered (a non-seed n' &lt;= n has "
               "witness pair with larger factor M &lt;= (n'+1)/2 &lt; n already "
               "discovered and hence expanded while the heap minimum was still "
               "below n, inserting n'). Every pair (a,b) with product &lt;= X is "
               "consumed at the expansion of its larger factor M &lt;= (X+1)/2, "
               "whose partner min(a,b) &lt;= min(M, X/M) &lt;= sqrt(X) is then "
               "present in the small list; so expansion against "
               "A ^ [1, sqrt(X)] misses nothing. &#9633;"))
story.append(P("<b>Cross-check [COMPUTED].</b> Independent naive fixpoint "
               "iteration reproduces the DP census exactly on [1,3000] "
               "(|A| = 1358 on both sides). Production run at X = 10^8: "
               "6 min 31 s wall time, pure Python standard library."))

# ----------------------------------------------------------------------
# 3 Lemma A
# ----------------------------------------------------------------------
story.append(P("3. Lemma A: the modular obstruction and the 2/3 ceiling", S_H1))
story.append(P("<b>Lemma A [PROVEN].</b> No element of A is congruent to "
               "1 modulo 3. <i>Proof.</i> Work in Z/3. The seed residues 2 and "
               "0 both lie in S = {0,2}. For r,s in S: if r = 0 or s = 0 then "
               "rs - 1 = -1 = 2 (mod 3); if r = s = 2 then rs - 1 = 3 = 0 "
               "(mod 3). Hence S is closed under the operation and contains the "
               "seeds, so by minimality the residues of A lie in S: never 1 "
               "modulo 3. &#9633;"))
story.append(P("<b>Corollary [PROVEN].</b> Upper density d*(A) &lt;= 2/3 = "
               "0.666667: each admissible class carries at most N/3 + O(1) "
               "elements below N."))
story.append(P("<b>Census check [COMPUTED].</b> Zero of the 55,939,931 elements "
               "below 10^8 are 1 mod 3. Note A is a proper subset of the allowed "
               "classes: e.g. 6, 11, 62 are not in A although none is 1 mod 3 "
               "(their n+1 admit no divisor pair from A x A)."))

# ----------------------------------------------------------------------
# 4 residues
# ----------------------------------------------------------------------
story.append(P("4. Residue sets modulo arbitrary moduli", S_H1))
story.append(P("<b>Proposition 3 [PROVEN].</b> For every modulus m the residue "
               "set {a mod m : a in A} equals exactly the minimal closed set S_m "
               "generated from {2 mod m, 3 mod m}. <i>Proof.</i> Containment: "
               "reduction commutes with the operation, so generation trees reduce "
               "into any closed set containing the seed residues. Reverse: every "
               "element of S_m arises after finitely many closure steps from the "
               "seeds, and each step lifts back through actual elements of A by "
               "induction on the step count. &#9633; Consequently d*(A) &lt;= "
               "|S_m|/m for every m, with CRT combination across coprime moduli."))

res_rows = [["modulus m", "|S_m|", "|S_m|/m", "remark"],
            ["3", "2", "0.666667", "S_3 = {0,2}: Lemma A"],
            ["9", "6", "0.666667", "{0,2,3,5,6,8}: repackages mod 3"],
            ["all other primes p <= 500 (94)", "p", "1",
             "S_p = Z/p, full set"],
            ["composite 4..500, m not in {9}", "-", "> 2/3",
             "none beats 2/3"]]
story.append(table(res_rows, [52 * mm, 22 * mm, 26 * mm, 74 * mm]))
story.append(P("Table 1. Closed residue sets [COMPUTED]: 95 primes and all "
               "composite moduli up to 500 scanned. Only m = 3 is proper; the "
               "best proven ceiling remains 2/3 and the residue method is "
               "saturated at small heights.", S_CAP))

# ----------------------------------------------------------------------
# 5 Lemma B
# ----------------------------------------------------------------------
story.append(P("5. Lemma B: an explicit logarithmic lower bound", S_H1))
story.append(P("Two families live in A [PROVEN]: P_k = 2^k + 1 (k &gt;= 1), the "
               "orbit of 3 under x |-> 2x - 1 (since t - 1 doubles along the "
               "orbit), and V_j = (3^(j+1)+1)/2 (j &gt;= 1), the orbit of 2 "
               "under x |-> 3x - 1 (fixed point 1/2: t_k - 1/2 = 3^k (2 - 1/2)). "
               "Closure produces all pairwise images."))
story.append(P("<b>Lemma B [PROVEN].</b> For N &gt;= 8, "
               "F(N) &gt;= floor((floor(log2 N) - 1)^2 / 4) &gt;= (log2 N - 2)^2/4 "
               "= (ln N)^2/(4 ln^2 2) + O(ln N), with explicit constant "
               "c = 1/(4 ln^2 2) = 0.5203."))
story.append(P("<i>Proof.</i> Consider z(i,j) = (2^(i+1)+1)(2^(j+1)+1) - 1 for "
               "integers 0 &lt;= i &lt;= j; all lie in A by two applications of "
               "closure, and z = 2^(i+j+2) + 2^(i+1) + 2^(j+1). "
               "<b>Distinctness.</b> If i &lt; j then z = 2^(i+1) (1 + 2^(j-i) + "
               "2^(j+1)) with odd bracket, so v2(z) = i+1 and odd part q = "
               "1 + 2^(j-i) + 2^(j+1). If i = j &gt;= 1 then z = 2^(i+2)(2^i+1): "
               "v2(z) = i+2, odd part 2^i + 1. The degenerate pair (0,0) gives "
               "z = 8 = 2^3, the only pure power of two in the family (every "
               "off-diagonal entry has odd part q &gt;= 11 and value &gt;= 14; "
               "every diagonal entry with i &gt;= 1 has odd part 2^i + 1 &gt; 1 "
               "and value &gt;= 24). Suppose z(i,j) = z(i',j'). Off-diagonal vs "
               "off-diagonal: equal v2 forces i = i', and equality of odd parts "
               "reads 2^(j-i) (1 + 2^(i+1)) = 2^(j'-i) (1 + 2^(i+1)); cancelling "
               "the odd integer forces j = j'. Diagonal vs diagonal: equal v2 "
               "forces i = i'. Off-diagonal vs diagonal would force simultaneously "
               "i+1 = i'+2 and 1 + 2^d + 2^(d+i+1) = 2^i' + 1, i.e. "
               "2^d (1 + 2^(i+1)) = 2^i' with d &gt;= 1: impossible since a pure "
               "power of two cannot be divisible by the odd integer "
               "1 + 2^(i+1) &gt;= 3. Hence the map is injective. "
               "<b>Counting.</b> Let lambda = floor(log2 N); whenever s := i+j+3 "
               "&lt;= lambda, z &lt;= 2^(s-1) + 2^(s-2) + 2^(s-2) = 2^s with "
               "strict inequality (equality would force s = 2(s-2)+3), so "
               "z &lt; 2^s &lt;= N. The pairs with i &lt;= j, i+j &lt;= lambda-3 "
               "number sum_{s=0}^{lambda-3}(floor(s/2)+1) = "
               "floor((lambda-1)^2/4). &#9633;"))
story.append(P("<b>Mixed family [COMPUTED; injectivity unproven].</b> With "
               "U_i = 2^(i+1)+1 and V_j = (3^(j+1)+1)/2, the values w(i,j) = "
               "U_i V_j - 1 all lie in A; a full injectivity proof would raise "
               "the constant to 1/(2 ln 2 ln 3) = 0.6566 (ln N)^2. The 2-adic "
               "cascade recovers min(i+1, v2(V_j - 1)) but ties block complete "
               "recovery. Computed up to 10^8: 216 values, zero collisions, all "
               "in A; the proven family contributes 168 values against the "
               "proven floor 156. Both bounds are exponentially far from the true "
               "F(10^8) = 55,939,931: their value is unconditional methodology, "
               "not approximation."))

# ----------------------------------------------------------------------
# 6 census
# ----------------------------------------------------------------------
dc = SUMMARY["decade_cumulative"]
hi = SUMMARY["decade_harmonic_increments"]
le = SUMMARY["local_exponents"]
g = SUMMARY["growth"]

story.append(P("6. Exact census up to 10^8", S_H1))
cen_rows = [["k", "F(10^k)", "F(10^k)/10^k", "local exp", "harm incr", "delta_hat"]]
for idx in range(8):
    k = idx + 1
    cen_rows.append([str(k), f"{dc[idx]:,}",
                     f"{dc[idx] / 10 ** k:.6f}",
                     f"{le[idx - 1]:.4f}" if idx else "-",
                     f"{hi[idx]:.4f}",
                     f"{hi[idx] / 2.302585093:.4f}"])
story.append(table(cen_rows, [14 * mm, 34 * mm, 34 * mm, 26 * mm, 28 * mm, 26 * mm]))
story.append(P("Table 2. Exact per-decade census [COMPUTED]. local exp = "
               "log(F(10^k)/F(10^(k-1)))/log 10; harm incr = sum of 1/b over "
               "A ^ (10^(k-1), 10^k]; delta_hat = incr / ln 10 estimates density.",
               S_CAP))
story.append(P("Reading of the data [COMPUTED trend; OPEN conclusion]: raw "
               "density rises in every decade; local exponents descend toward 1 "
               "from above (top value %.4f); per-decade harmonic mass approaches "
               "delta_hat ln 10 with delta_hat climbing through 0.56. A log-log "
               "least-squares fit over decades 4-8 gives alpha_OLS = %.5f +- "
               "0.00254 with R^2 = %.5f, consistent with near-linear growth "
               "F(N) ~ c_N N and drifting density. All trends are compatible "
               "with convergence of F(N)/N to a positive limit &lt;= 2/3; "
               "neither existence nor positivity of the limit is provable by "
               "these means."
               % (le[-1], g["alpha_ols"], g["ols_R2"])))
story.append(P("Additional exact facts within the completely stored range "
               "[1, 10^6] (F = 535,585) [COMPUTED]: first elements 2, 3, 5, 8, "
               "9, 14, 15, 17, 23, 24, 26, ...; smallest non-members 1, 4, 6, 7, "
               "10, 11, 12, 13, 16, 18, ...; maximal gap between consecutive "
               "elements is 10 (2159 to 2169); conditional density inside "
               "allowed classes {n not 1 mod 3} rises monotonically: 0.591, "
               "0.634, 0.721, 0.773, 0.803 at N = 10^2, ..., 10^6."))

# ----------------------------------------------------------------------
# 7 heuristic
# ----------------------------------------------------------------------
story.append(P("7. Mean-field heuristic: derivation and empirical rejection",
               S_H1))
story.append(P("Membership is an OR over divisor pairs (Theorem 1): n is in A "
               "iff n+1 = ab for some a,b in A (or n in {2,3}). Assume "
               "<b>(H1)</b> equidistribution: for each b, "
               "|A ^ [1,M] ^ (-1 mod b)| ~ F(M)/b uniformly in b. Counting "
               "candidate images ba - 1 &lt;= N over all b in A gives "
               "F(N) ~ sum_{b in A} F(N/b)/b. Inserting the ansatz "
               "F(N) ~ c N^alpha and cancelling yields the self-consistency "
               "equation <b>(*)</b>:  sum_{b in A} b^-(1+alpha) = 1. Because the "
               "truncated harmonic sum diverges like delta_hat ln X (computed "
               "H_X = 9.1036 at X = 10^8, increments approaching 1.287 per "
               "decade), the left side decreases continuously from infinity to "
               "zero, so under (H1) a unique alpha* &gt; 0 exists <b>[HEURISTIC]</b>."))
story.append(P("<b>Numerics [COMPUTED].</b> Exact truncated sums below "
               "2*10^5 and 64 logarithmic buckets per decade above give "
               "alpha*_trunc(10^8) = %s (root residual +2.5e-11; stable: 0.472709 "
               "already at X = 10^6). The integral surrogate delta 2^-alpha / "
               "alpha = 1 gives alpha*(delta = 0.5594) = 0.4185 and "
               "alpha*(delta = 2/3) = 0.4785."
               % g["alpha_star_trunc"]))
story.append(P("<b>Rejection [COMPUTED vs HEURISTIC].</b> The mean field "
               "predicts F(10^8) ~ (10^8)^0.4734 = 6,131 against the exact "
               "55,939,931: off by factor 9,124. Simultaneously the direct fit "
               "sits at alpha_OLS = 1.016 &gt; 1 &gt; alpha*. Two mechanisms "
               "identify the failure: (1) <i>self-affine imaging</i> - each "
               "b in A transports a near-copy {ba - 1 : a in A} into A, so "
               "membership correlations inflate density beyond products of "
               "marginals (the OR-condition over divisor pairs); (2) "
               "<i>modular rigidity</i> - equidistribution fails absolutely on "
               "class 1 mod 3, and Proposition 3 formalizes such constraints for "
               "every modulus. Equation (*) therefore describes a random model "
               "of A, not A itself. Its interest is negative but sharp: "
               "GREEN-036 is not governed by pseudorandom multiplicative "
               "statistics, and any successful approach must exploit the "
               "correlated, self-affine structure."))

# ----------------------------------------------------------------------
# 8 outlook
# ----------------------------------------------------------------------
story.append(P("8. Outlook: what is missing", S_H1))
story.append(P("<b>[OPEN]</b> To prove d(A) &gt; 0 one wants F(N) &gt;= cN, "
               "plausibly via eventual containment of an arithmetic progression "
               "of allowed class, or a bootstrap converting lower density at "
               "height T into higher density at height T' &gt; T. Visible "
               "obstructions: 6, 11, 62 are absent despite allowed residues and "
               "the gap 2159-2169 shows early holes, so any progression claim "
               "needs a threshold phenomenon. To prove d(A) = 0 one must reverse "
               "a trend rising across eight decades of exact computation; no "
               "mechanism suggests itself. Between the two: the only proven "
               "ceiling is 2/3 (Lemma A), the residue method is exhausted for "
               "m &lt;= 500, and the proven growth floor is "
               "(ln N)^2/(4 ln^2 2). Any genuinely new constraint - larger-"
               "modulus rigidity, p-adic restrictions, complement stability - "
               "would constitute real progress on GREEN-036."))

# ----------------------------------------------------------------------
# 9 attack iteration (obstructions + rigidity)
# ----------------------------------------------------------------------
story.append(P("9. Attack iteration: obstructions and rigidity", S_H1))
story.append(P("<b>L1 (image counting cap).</b> T_b(x) = bx - 1 is injective, so "
               "|T_b(A) cap [1,N]| = F(floor((N+1)/b)) exactly; and "
               "|(T_b1 A) cap (T_b2 A) cap [1,N]| &lt;= floor((N+1)/lcm(b1,b2)). "
               "The pairwise overlap load over seeds b &lt;= B satisfies "
               "S(B) = sum gcd(b1,b2)/(b1 b2) = (1/pi^2)(log B)^3 + O((log B)^2) "
               "(phi-identity), so Bonferroni's positive part collapses once "
               "(log B)^3 / pi^2 &gt;~ delta log B: images of a dense low-scale "
               "region cannot certify density growth. Finite evidence at "
               "X = 2e6: |(3A-1) cap (5A-1)| = 132,814 &lt;= 133,333 (99.6% tight)."))
story.append(P("<b>L2 (multiplication-table cap; no one-step bootstrap).</b> By "
               "Erdos 1960 (quantified by Ford, Annals 2008): M(N) = |{ab: a,b &lt;= N}| "
               "= N^2/(log N)^delta_F (log log N)^{3/2}, delta_F = 1 - (1+log log 2)/log 2 "
               "= 0.08607. Restricting to any S x S, S subset [2,N], only shrinks the "
               "table and ab -&gt; ab - 1 is a value bijection; hence one closure step on "
               "ANY dense seed yields relative density o(1) at height N^2. No implication "
               "F(N) &gt;= delta N =&gt; F(N^2) &gt;= Phi'(delta) N^2 follows from the closure rule "
               "alone: density at height N^2 must be built through ~log N intermediate scales."))
story.append(P("<b>L3 (complement propagation along primes).</b> If p is prime and "
               "p notin A, then pq - 1 notin A for every prime q (semiprime pq has no "
               "other factor pairs). Anchor: 11 notin A since 12 = 2*6 = 3*4 with 4, 6 out. "
               "All 9,592 numbers 11q - 1 (q prime &lt;= 1e5) are outside A (finite "
               "evidence). Such families count O(N/log N): propagation complements have "
               "density 0 and cannot obstruct d(A) &gt; 0."))
story.append(P("<b>L4 (2-chain test; prime rigidity).</b> For m &gt;= 2: 2m - 1 in A iff "
               "m in A or some other divisor pair (a,b) of 2m lies in A x A. In particular "
               "for primes p &gt;= 5: p in A &lt;=&gt; qp - 1 in A for every prime q != p."))
story.append(P("<b>L5 (powers of two; finite evidence).</b> Exact memoized recursion gives, "
               "for k &lt;= 40: 2^k in A iff k in {1, 3, 9, 15, 17, 21, 23, 25, 27, 29, 33, 35, 39}. "
               "No even k &gt; 0 occurs; odd k cascade through (2^k+1)/3 with unbounded "
               "certificate depth - e.g. 512 in A via 513 = 3*171, 172 = 2*86, 87 = 3*29, "
               "30 = 2*15, 16 = 2*8, 9 = 3*3 (depth &gt;= 5). No bounded-depth local rule captures A."))
story.append(P("<b>The GAP.</b> Nothing lower-bounds the count of n &lt;= X for which n+1 has "
               "a divisor pair in A x A beyond the O((log X)^2) families of Lemma B; positive "
               "density requires at least cX such n. Status after this iteration: STILL OPEN, "
               "with sharpened obstruction theory.", S_NOTE))

story.append(P("<b>Reproducibility.</b> Everything regenerates by "
               "python3 verify_solution.py [X] (default X = 10^7, about 20 s; "
               "production X = 10^8, 6.5 min, nine of nine checks passed). "
               "Artifacts: data/census_summary.json, data/census.csv.gz (first "
                "10^6 elements), data/run_output.txt reproduced verbatim in the "
                "Appendix; targeted structural checks regenerate by "
                "attack_verify.py (output also in the Appendix). Standard "
                "library only; deterministic.", S_NOTE))
story.append(P("The complete dossier is version-controlled at "
               '<link href="https://github.com/GamebP/MathProblems/tree/main/GREEN-036">'
               "https://github.com/GamebP/MathProblems/tree/main/GREEN-036</link>, "
               "mirroring this folder file-for-file.", S_NOTE))

story.append(PageBreak())

# ----------------------------------------------------------------------
# appendix
# ----------------------------------------------------------------------
story.append(P("Appendix. Verbatim verifier output (production run, X = 10^8)",
               S_H1))
wrapped = []
for line in RUNLOG.splitlines():
    line = line.rstrip()
    if len(line) <= 118:
        wrapped.append(line)
    else:
        wrapped.extend(textwrap.wrap(line, 118, subsequent_indent="      ",
                                     drop_whitespace=False))
story.append(Preformatted("\n".join(wrapped), S_MONO))

ATTACKLOG = (HERE / "data" / "attack_output.txt").read_text()
story.append(P("Appendix B. Verbatim attack-check output (attack_verify.py, X = 2e6)",
               S_H1))
wrapped = []
for line in ATTACKLOG.splitlines():
    line = line.rstrip()
    if len(line) <= 118:
        wrapped.append(line)
    else:
        wrapped.extend(textwrap.wrap(line, 118, subsequent_indent="      ",
                                     drop_whitespace=False))
story.append(Preformatted("\n".join(wrapped), S_MONO))

doc = SimpleDocTemplate(
    str(HERE / "report.pdf"), pagesize=A4,
    leftMargin=22 * mm, rightMargin=22 * mm,
    topMargin=20 * mm, bottomMargin=20 * mm,
    title="GREEN-036 Multiplicatively Closed Set Density",
    author="research dossier")
doc.build(story)
print("wrote report.pdf,", (HERE / 'report.pdf').stat().st_size, "bytes")

# report.tex carries its own inline verbatim copy of RUNLOG; keep it in sync
# if data/run_output.txt ever changes (byte-exact block between \begin/\end).
assert not any(line.strip() == r"\end{verbatim}" for line in RUNLOG.splitlines())
